package com.github.shicloud.jdbc.templete;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.springframework.jdbc.core.PreparedStatementCreator;

/**
 * 返回主键的PreparedStatementCreator
 *
 */
public class ReturnIdPreparedStatementCreator implements PreparedStatementCreator {

	private String sql;
	private Object[] params;
	private String autoGeneratedColumnName;

	public ReturnIdPreparedStatementCreator(SqlParamsPairs sqlParamsPairs, String autoGeneratedColumnName){
		this.sql = sqlParamsPairs.getSql();
		this.params = sqlParamsPairs.getParams();
		this.autoGeneratedColumnName = autoGeneratedColumnName;
	}
	
	public PreparedStatement createPreparedStatement(Connection connection)
			throws SQLException {
		PreparedStatement ps = connection.prepareStatement(sql, new String[] {autoGeneratedColumnName});
        for (int i = 0; i < params.length; i++) {
			Object value = params[i];
			ps.setObject((i+1), value);
		}
        return ps;
	}

}
